[project]
name = "hazy-oracles-user-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aidan Dempster", email = "aidan.dempster@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "better-profanity>=0.7.0",
    "detoxify>=0.5.2",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "graphviz>=0.21",
    "httpx>=0.28.1",
    "httpx2>=2.13.1",
    "igraph>=1.0.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "networkx>=3.6.1",
    "pygarble>=0.8.0",
    "pytest>=9.1.1",
    "scipy>=1.18.1",
    "sqlmodel>=0.0.39",
    "unidecode>=1.4.0",
]

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"
